eno = int(input("Enter a your employee Number: "))
ename = input("Enter Your  Name: ")
esal = float(input("Enter your salary: "))
eaddr = input("Enter Your address: ")
married = bool(input("Are you Married ?say(True/False): "))
print("Congrats☻!", ename ,"your successully regesterd for employee")
print("Your Employee Name is: ",ename)
print("Your Employee Number is: ",eno)
print("Your Employee salary is: ",esal)
print("Your Employee  Adrres is: ",eaddr)
print("Your Marital status is : ",married)
